######################################################################
# Automatically generated by qmake (3.0) ?? ??? 20 10:43:45 2018
######################################################################

TEMPLATE = app
TARGET = main
INCLUDEPATH += .

include($$(SOUIPATH)/demo_com.pri)
DESTDIR = ../bin

# Input
SOURCES += main.cc
